sudo: true
language: python
python:
  - 2.7
services:
  - mysql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-dev libmysqlclient-dev
  - mysql -e 'CREATE DATABASE dstore_test;'
install:
  - pip install -q -r dev_requirements.txt
  - pip install coveralls
script:
  - nosetests -vs tests --with-coverage --cover-package=dstore_mysql
after_success:
  - coveralls
