sudo: true
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
services:
  - mysql
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get -qq update; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install -y python-dev libmysqlclient-dev; fi
  - mysql -e 'CREATE DATABASE dstore_test;'
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install MySQL-python; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install pymysql; fi
  - pip install -q -r dev_requirements.txt
  - pip install coveralls
script:
  - nosetests -vs tests --with-coverage --cover-package=dstore_mysql
after_success:
  - coveralls
