sudo: true
language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
services:
  - mysql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-dev libmysqlclient-dev
  - mysql -e 'CREATE DATABASE dstore_test;'
install:
  - pip install -q -r dev_requirements.txt
script:
  - nosetests -vs tests
